<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTfJgpBk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTfJgpBk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTfJgpBk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTfJgpBk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTfJgpBk\App_KernelDevDebugContainer([
    'container.build_hash' => 'TfJgpBk',
    'container.build_id' => '10ca4e0f',
    'container.build_time' => 1678041028,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTfJgpBk');
